version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda
      POSTGRES_DB: camunda
    ports:
      - "5433:5432"  # Host port 5433 mapped to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  camunda-node1:
    image: camunda/camunda-bpm-platform:latest
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=postgres:5432
      - CAMUNDA_WEBAPP_CSRF_ENABLED=false
    volumes:
      - ./camunda.cfg.xml:/camunda/conf/camunda.cfg.xml 
    ports:
      - "8581:8080"  # Host port 8581 mapped to container port 8080
    depends_on:
      - postgres

  camunda-node2:
    image: camunda/camunda-bpm-platform:latest
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=postgres:5432
      - CAMUNDA_WEBAPP_CSRF_ENABLED=false
    ports:
      - "8582:8080"  # Host port 8582 mapped to container port 8080
    volumes:
      - ./camunda.cfg.xml:/camunda/conf/camunda.cfg.xml 
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "8580:80"  # Host port 8580 mapped to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - camunda-node1
      - camunda-node2

volumes:
  postgres_data:
